### PR TITLE
[CIRC-312] Request status is not changed after check-in

### PR DESCRIPTION
**Pull request by opochepam**
## Purpose
Resolves: [CIRC-312](https://issues.folio.org/browse/CIRC-312)
Request status is not changed after check-in

## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [x] Code coverage on new code is 80% or greater
  - [x] Duplications on new code is 3% or less
  - [x] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [x] Were any API paths or methods changed, added or removed?
  - [x] Were there any schema changes?
  - [x] Did any of the interface versions change?
  - [x] Were permissions changed, added, or removed?
  - [x] Are there new interface dependencies?
  - [x] There are no breaking changes in this PR.

### CODE REVIEW

**Comment by marcjohnson-kint** [comment]
That's interesting, I did wonder if the values needed quoting in all circumstances.

How do you know this resolves the issue?

Is there an API test to demonstrate the desired behaviour?

And this test did not fail due to a difference in actual behaviour vs. the fakes? (and I can lament not being able to run the API tests against real implementations again)

**Comment by opochepam** [comment]
> That's interesting, I did wonder if the values needed quoting in all circumstances.
> 
> How do you know this resolves the issue?
> 
> Is there an API test to demonstrate the desired behaviour?
> 
> And this test did not fail due to a difference in actual behaviour vs. the fakes? (and I can lament not being able to run the API tests against real implementations again)

To resolve the issue I checked the SQL query generated from CQL query in mod-circulation-storage. The condition responsible for `Open - Not yet filled` request status is following:
`(lower(f_unaccent(request.jsonb->>'status')) LIKE lower(f_unaccent('Open -')))) AND ( (lower(f_unaccent(request.jsonb->>'status')) LIKE lower(f_unaccent('yet filled'))) IS NOT TRUE))`

I suppose some cql2pgjson-java update could cause the issue. In my understanding the parser considers `Not` as CQL keyword. Then I tried to quote request status values and the part of a query we're interested in became following:
`(lower(f_unaccent(request.jsonb->>'status')) LIKE lower(f_unaccent('Open - Not yet filled'))))`

I am not aware of any API tests which checks this functionality.

**Comment by marcjohnson-kint** [comment]
> > That's interesting, I did wonder if the values needed quoting in all circumstances.
> > How do you know this resolves the issue?
> > Is there an API test to demonstrate the desired behaviour?
> > And this test did not fail due to a difference in actual behaviour vs. the fakes? (and I can lament not being able to run the API tests against real implementations again)
> 
> To resolve the issue I checked the SQL query generated from CQL query in mod-circulation-storage. The condition responsible for `Open - Not yet filled` request status is following:
> `(lower(f_unaccent(request.jsonb->>'status')) LIKE lower(f_unaccent('Open -')))) AND ( (lower(f_unaccent(request.jsonb->>'status')) LIKE lower(f_unaccent('yet filled'))) IS NOT TRUE))`
> 
> I suppose some cql2pgjson-java update could cause the issue. In my understanding the parser considers `Not` as CQL keyword. Then I tried to quote request status values and the part of a query we're interested in became following:
> `(lower(f_unaccent(request.jsonb->>'status')) LIKE lower(f_unaccent('Open - Not yet filled'))))`
> 

What could be useful would be to change the fake CQL implementation in mod-circulation to reflect this behaviour in some way. Maybe to disallow unquoted values when there are spaces?

> I am not aware of any API tests which checks this functionality.

I was referring to API tests that check the functionality for page requests. I imagine there are tests that pass for this behaviour incorrectly because the fake CQL implementation is different to the real implementation 

(and then I am reminded of how this used to be caught by running the tests against the real modules, however that is no longer possible :-( )

**Comment by marcjohnson-kint** [comment]
Did you try out any other scenarios, for example, what happens if a query for a numeric value is quoted? (I'm not sure if circulation uses any of those)

**Comment by opochepam** [comment]
> What could be useful would be to change the fake CQL implementation in mod-circulation to reflect this behaviour in some way. Maybe to disallow unquoted values when there are spaces?

What do you mean by fake CQL implementation in mod-circulation? Fake implementation of endpoint which accepts CQL query as a parameter?

> Did you try out any other scenarios, for example, what happens if a query for a numeric value is quoted? (I'm not sure if circulation uses any of those)

No I did't. I just tried to quote values to make CQL parser ignore `Not` keyword.

**Pull request merged**
