### PR TITLE
CIRC-999: Do not attempt to calculate due date when loan is not loanable nor renewable

### PR DESCRIPTION
**Pull request by bohdan-suprun**
https://issues.folio.org/browse/CIRC-999 - Redundant renewal failure reasons display

## Purpose
A redundant renewal failure reasons is displayed when we attempt to calculate new dueDate for non loanable or non renewable loan policies. For such loan policies we should not calculate new due date at all, because the policy does not have some required properties needed for that process: policy profile, renew from, closed library due date management, etc.

## Approach
* Do not calculate new due date on renew when loan policy is non loanable or non renewable.

## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Comment by marcjohnson-kint** [comment]
@bohdan-suprun I wasn't sure if this approach had been agreed with Emma during refinement, have you confirmed with her that it's ok to short circuit accumulation of errors for these specific errors?

**Comment by bohdan-suprun** [comment]
> @bohdan-suprun I wasn't sure if this approach had been agreed with Emma during refinement, have you confirmed with her that it's ok to short circuit accumulation of errors for these specific errors?

No, but the story says to do so: 
> **Expected Results:** Renewal fails. Renewal status: Item not renewed: item is not loanable

**Comment by marcjohnson-kint** [comment]
@bohdan-suprun Please check with Emma. 

As I understand it, this issue came about because the requirements for [https://issues.folio.org/browse/CIRC-956](CIRC-956) were incomplete and this immediate short-circuiting was the previous behaviour.

I'm concerned we might not line up with the requirements that Emma shared in the spreadsheet on [https://issues.folio.org/browse/UIU-1930](UIU-1930) again and it will need rework.

**Comment by bohdan-suprun** [comment]
@marcjohnson-kint, ok I'll check.

**Comment by marcjohnson-kint** [comment]
> @marcjohnson-kint, ok I'll check.
> 
> > this immediate short-circuiting was the previous behaviour.
> 
> We should still return multiple reasons, but if loan is not loanable or not renewable we just not execute the last step - calculate due date, because the loan policy don't have enough data to initiate this process, so there will be some failures that more like related to internal implementation. For other cases the due date should be calculated and calculated errors should be appended to the list, if any.

Sure. Please can you confirm that behaviour with Emma. I don't think the single example in the issue is sufficient to general it to that degree.

**Review by marcjohnson-kint — APPROVED** [review]

**Pull request merged**
