### PR TITLE
Circ 255 Disallow >1 Open Request on Same Item by Same Requester

### PR DESCRIPTION
**Pull request by Anatolii-Starkov**
-Added validator for creation a request
-Added tests
-Added constructor to ValidationErrorFailure.java with a massage parameter only

### CODE REVIEW

**Comment by marcjohnson-kint** [comment]
Did this change really affect 54 files or are some of them changes to import ordering or formatting?

**Comment by Anatolii-Starkov** [comment]
No it didn't, I had bloody merge with master and probably something went wrong 😄 
I will raise this PR one more time without unnecessaries changes.

**Comment by marcjohnson-kint** [comment]
@Anatolii-Starkov I feel your pain :-(

If you want to submit the formatting changes as a quick separate change before hand, I can review that.

Or we can make an exception and just ignore the formatting changes?

**Comment by Anatolii-Starkov** [comment]
I think it will be better for all if I remove this branch and create it again without formatted files. For exceptional case I have one little reformatted class that I could not leave as is 😈

**Pull request closed without merging**
