### PR TITLE
CIRC-363 Increase calendar interface dependency version

### PR DESCRIPTION
**Pull request by dmytrotur**
## Purpose
Increase calendar interface dependency version from **2.0** to **3.0**.
Has to be merged together with https://github.com/folio-org/mod-calendar/pull/85
## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [x] Code coverage on new code is 80% or greater
  - [x] Duplications on new code is 3% or less
  - [x] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [x] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [x] There are no breaking changes in this PR.

### CODE REVIEW

**Comment by dmytrotur** [comment]
> What changes have been made to the calendar interface?

Some of the module permissions were changed.
> What impact do they have on the use of the interface by this module?

No impact.
> There appears to be no code changes, does that mean that this module could be compatible with both 2.0 and 3.0 versions?

Yes. Should I specify both 2.0 and 3.0 in dependency?

> A quick inspection of the pull request for mod-calendar suggests the permissions have changed, does this mean the module permissions for endpoints in circulation need to change?

No, the endpoint used by mod-circulation remained unchanged.
 
> This change should have an issue for mod-circulation in JIRA, in order to track changes made during a particular release (it is not possible to associate a mod-calendar issue with a version change in mod-circulation)

Ok, I'll create one and link to this pull request.

**Comment by marcjohnson-kint** [comment]
> Yes. Should I specify both 2.0 and 3.0 in dependency?

Yes if the changes do not affect the part of the interface used by mod-circulation. Though see my comments on the mod-calendar pull request.

**Comment by dmytrotur** [comment]
@marcjohnson-kint Could this pull request be merged?
All other pull requests related to the change in mod-calendar are ready to merged.

**Comment by marcjohnson-kint** [comment]
> @marcjohnson-kint Could this pull request be merged?
> All other pull requests related to the change in mod-calendar are ready to merged.

Sure

**Pull request merged**
