### PR TITLE
CIRC-1154: Optimistic locking for instance, holdings, item 

### PR DESCRIPTION
**Pull request by julianladisch**
## Purpose

Allow these new required mod-inventory-storage interfaces:
item-storage 9.0
instance-storage 7.0
holdings-storage 4.0

They introduce the "_version" property for optimistic locking.
## Approach
Add the new interface version to the list of required versions.

In the unit tests amend InstanceBuilder, HoldingsBuilder and ItemBuilder to add this property.

## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [x] Code coverage on new code is 80% or greater
  - [x] Duplications on new code is 3% or less
  - [x] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [x] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

### CODE REVIEW

**Review by marcjohnson-kint — COMMENTED** [review]
There seem to be no changes to the test code in this pull request. 

How have these changes been tested to demonstrate that the module send a representation the `_version` property in the representations sent to the server when an item is changed during circulation processes?

**Comment by julianladisch** [comment]
https://github.com/folio-org/mod-circulation/blob/v20.1.6/src/main/java/org/folio/circulation/domain/Item.java#L43 stores the item JSON as a JsonObject. The `_version` property is passed through. This unit test shows that is properly works: https://github.com/folio-org/mod-circulation/pull/888/commits/cf04038f3eca56ee4090a41fd06b472f5c925053

**Comment by marcjohnson-kint** [comment]
> https://github.com/folio-org/mod-circulation/blob/v20.1.6/src/main/java/org/folio/circulation/domain/Item.java#L43 stores the item JSON as a JsonObject. The `_version` property is passed through. This unit test shows that is properly works: [cf04038](https://github.com/folio-org/mod-circulation/commit/cf04038f3eca56ee4090a41fd06b472f5c925053)

That's fair enough, an unfortunate design choice on my part means that this will likely work by accident. My preference would be for some specific tests to demonstrate that the version is included so if this code changes this specific part of the contract  with inventory is preserved.

Probably more important is a test that demonstrates what the system will do when a conflict occurs (when this module receives a 409 from the implementor of `item-storage` when trying to change an item).

**Review by MikhailFokanov-ebsco — APPROVED** [review]

**Comment by steveellis** [comment]
@marc-johnson The CP team would be grateful if you could approve this pull request. Right now it's the last remaining PR to be merged and is holding up functional testing for optimistic locking that we are hoping to get going this week.

Of course in principle I agree that more unit tests would be good, but I think right now perhaps we can agree that proceeding with functional tests is also important -- just to move [this epic lift](https://issues.folio.org/browse/UXPROD-3089) forward.

**Review by marcjohnson-kint — APPROVED** [review]
Approved at the request of the Core Platform (CP) team to expedite this work.

(I don't know why my approval was needed given that the CP team already approved it internally and my feedback was not accepted)

**Pull request merged**
