### PR TITLE
CIRC-1064 Remove override check out by barcode

### PR DESCRIPTION
**Pull request by alexanderkurash**
Resolves [CIRC-1064](https://issues.folio.org/browse/CIRC-1064)

## Purpose
The old `override check out by barcode` endpoint need to be removed now that we've implemented a single endpoint approach (override is done through the regular check out endpoint).

FE doesn't have a dependency on this interface anymore.

## Approach
Removed the endpoint, tests, increased major version of the circulation interface. Check out strategies were removed because now there's only one - regular strategy.

## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [x] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [x] Did any of the interface versions change?
  - [x] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Review by marcjohnson-kint — COMMENTED** [review]
Please update the major version for the module and include some news for that release

**Review by marcjohnson-kint — COMMENTED** [review]
Thank you for thoroughly removing the now redundant code

**Comment by marcjohnson-kint** [comment]
@alexanderkurash 

I am about to release a new minor version of mod-circulation and am trying to figure out if that can be done from the mainline. If this is merged then that definitely cannot happen.

Please can the Vega team hold off on merging this change for a little bit (no longer than today). 

I have added the `do not merge` label to this for the moment.

Thank you for considering my request.

**Comment by alexanderkurash** [comment]
> @alexanderkurash
> 
> I am about to release a new minor version of mod-circulation and am trying to figure out if that can be done from the mainline. If this is merged then that definitely cannot happen.
> 
> Please can the Vega team hold off on merging this change for a little bit (no longer than today).
> 
> I have added the `do not merge` label to this for the moment.
> 
> Thank you for considering my request.

Sure, we can wait. Does it mean that we'd need to update major version to 22.0.0 in this PR?

**Comment by marcjohnson-kint** [comment]
> Does it mean that we'd need to update major version to 22.0.0 in this PR?

No, the release I make will be `20.1.0`, the mainline will move to `20.2.0` and this change will still move it `21.0.0`

Does that make sense?

**Comment by alexanderkurash** [comment]
> > Does it mean that we'd need to update major version to 22.0.0 in this PR?
> 
> No, the release I make will be `20.1.0`, the mainline will move to `20.2.0` and this change will still move it `21.0.0`
> 
> Does that make sense?

Oh, I thought you were releasing next major version, sorry. Yes, totally makes sense.

**Comment by marcjohnson-kint** [comment]
@alexanderkurash I've removed the `do not merge` label as CIRC-1077 is going to be released from a branch meaning this can be merged to the mainline prior to this release.

**Review by roman-barannyk — APPROVED** [review]

**Pull request merged**
