### PR TITLE
CIRC-862: Save date and time when loan is aged to lost

### PR DESCRIPTION
**Pull request by bohdan-suprun**
https://issues.folio.org/browse/CIRC-862 - Backend: Aged to lost action on loan details

## Approach
* Require `loan-storage` of `7.1` version;
* Set `loan.agedToLostDate` when a loan is being aged to lost.

## Pre-Merge Checklist:
Before merging this PR, please go through the following list and take appropriate actions.

- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] Were any API paths or methods changed, added or removed?
  - [ ] Were there any schema changes?
  - [ ] Did any of the interface versions change?
  - [ ] Were permissions changed, added, or removed?
  - [ ] Are there new interface dependencies?
  - [ ] There are no breaking changes in this PR.
  
If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?  
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.  

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Comment by bohdan-suprun** [comment]
> This change appears to be about remembering when a borrowed item was aged to lost. How does that relate to an action, as far as I can tell, the actions were already being produced?

There is a scenario in jira that tells that the date should be displayed in the Lost field. But you're right this is not related to a history record.

**Comment by marcjohnson-kint** [comment]
> > This change appears to be about remembering when a borrowed item was aged to lost. How does that relate to an action, as far as I can tell, the actions were already being produced?
> 
> There is a scenario in jira that tells that the date should be displayed in the Lost field. But you're right this is not related to a history record.

Where in the UI is that date intended to be displayed?

Is it on the loan action history, in which case, is it not the date of the action, or is it elsewhere?

**Comment by bohdan-suprun** [comment]
> Where in the UI is that date intended to be displayed?
> 
> Is it on the loan action history, in which case, is it not the date of the action, or is it elsewhere?

Jira scenario 2:

> 2. Scenario
>    * Given a loan for an item that has aged to lost
>    * When viewing the loan details
>    * Then populate the Lost field with the date and time the item aged to lost

**Comment by marcjohnson-kint** [comment]
> > Where in the UI is that date intended to be displayed?
> > Is it on the loan action history, in which case, is it not the date of the action, or is it elsewhere?
> 
> Jira scenario 2:
> 
> > 1. Scenario
> >    
> >    * Given a loan for an item that has aged to lost
> >    * When viewing the loan details
> >    * Then populate the Lost field with the date and time the item aged to lost

Is that field populated for when an item is declared lost whilst it is on loan?

**Comment by marcjohnson-kint** [comment]
Can this be closed, following this [conversation](https://folio-project.slack.com/archives/GF883BB4Y/p1596560513167200?thread_ts=1596560444.165300&cid=GF883BB4Y)?

**Comment by bohdan-suprun** [comment]
> Can this be closed, following this [conversation](https://folio-project.slack.com/archives/GF883BB4Y/p1596560513167200?thread_ts=1596560444.165300&cid=GF883BB4Y)?

Sure, closing it.

**Pull request closed without merging**
